workflows:
    react-native:
        name: 'CodeMagic'
        environment:
            node: v16.18.0
            groups:
              - api
        triggering:
            events:
                - push
                - tag
                - pull_request
        scripts:
            - npm install
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"